<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.grant</groupId>
        <artifactId>johnny-johnny</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>chat-rules</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.grant</groupId>
            <artifactId>chat-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-engine</artifactId>
            <version>${drools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-xml-support</artifactId>
            <version>${drools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie</groupId>
            <artifactId>kie-api</artifactId>
            <version>${drools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/org.drools/drools-mvel -->
		<dependency>
			<groupId>org.drools</groupId>
			<artifactId>drools-mvel</artifactId>
			<version>10.1.0</version>
			<scope>compile</scope>
		</dependency>
    </dependencies>
</project>
