<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.grant</groupId>
        <artifactId>johnny-johnny</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>chat-llm</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.grant</groupId>
            <artifactId>chat-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.openai</groupId>
            <artifactId>openai-java</artifactId>
            <version>${openai.java.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-openai-spring-boot-starter</artifactId>
			<version>1.0.0-M6</version> <!-- Use the latest version available -->
		</dependency>
    </dependencies>
</project>
